### ISSUE TITLE
[Bug] SSH connection failure : Failed to validate host key

### ISSUE THREAD

**Issue by windware** [hankinsoft/SQLPro#149]
I'm getting some connection failure through SSH tunneling on the latest release from the official site.

I can SSH into the server from terminal fine and connect to MySQL and I'm specifying the private key from ~/.ssh/config and with SequelPro, it seems to connect fine too.

Server side's log says this single line,

Oct 11 19:49:31 "HOSTNAME" sshd["PID"]: Received disconnect from "IP": 11: Client disconnected. [preauth]

I've tried to delete SQLPro preferences on macOS but can't seem to really reset the app to the clean state.

I'm on macOS 10.13.

![screen shot 2017-10-11 at 19 43 23](https://user-images.githubusercontent.com/4352236/31436102-c5870158-aebc-11e7-8fa4-c49ab785369c.png)

**Comment by hankinsoft** [comment]
Fixed in https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.1.0.149.app.zip.

**Comment by windware** [comment]
OK. It fixed.

Does SQLPro handle its own set of fingerprints and not use the one already there as in ~/.ssh/known_hosts?

It would be nice if it uses the native ssh client (which would then also honor ~/.ssh/config) but I guess it's not so easy to have it cross platform that way.

**Comment by hankinsoft** [comment]
> Does SQLPro handle its own set of fingerprints and not use the one already there as in ~/.ssh/known_hosts?

A little bit of both actually. It should be honouring fingerprints if they are already in ~/.ssh/known_hosts, but due to sandboxing it cannot write to that file. So if a fingerprint does not exist, it will prompt to handle its own.

**Comment by bomb-on** [comment]
After 2 years I still have issues with this super annoying error. From connecting, over listing tables/views/functions, to issuing queries...

Do you have in plan to fix this once and for all because otherwise this is pretty unusable software which I overpaid in the first place and I'm afraid I'll just have to ask for refund or something.

Thanks in advance.
