### ISSUE TITLE
Not possible to use passwords that start with an equal sign

### ISSUE THREAD

**Issue by martijnt** [hankinsoft/SQLPro#256]
We use generated passwords for our DB accounts. We could connect without issue to all RDS instances, except for one. It turned out that the password for this one started with a '=' character. Changing the password resolved the issues for us

**Comment by hankinsoft** [comment]
That’s interesting. To confirm, your using Postgres in RDS? I’ll
investigate.

**Comment by martijnt** [comment]
Yes, Postgres 10.6 on RDS

**Comment by hankinsoft** [comment]
This should be fixed as of https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.06.06.app.zip? If you get the chance, please give its. try.

**Comment by martijnt** [comment]
Unfortunately it's not resolved in this version

**Comment by nakashimanh** [comment]
The password including /(slash) is also Not possible to log-in to database.
The app version is 2019.06.06 (Build 110490.1). It looks this starts from this version.

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.06.11.app.zip? If you are still running into issues, could you possibly generate a password which has issues? I've added test cases for = and / in this posted version and both are able to connect (the previous attempt at a fix, instead broke all special character).

**Comment by martijnt** [comment]
Still doesn't work, unfortunately. Tried creating a new connection just to be sure. Error message: 'FATAL:  password authentication failed for user "postgres"'. I verified It works in Tableplus using the same credentials

**Comment by hankinsoft** [comment]
Are you able to create + share a new password which you see this issue? Ive
been trying with =‘s and can’t seem to reproduce - I’m thinking it might be
a different character or a set of characters together.

**Comment by martijnt** [comment]
docker run -p 5432:5432 -e POSTGRES_PASSWORD="test" -d postgres 			# this works
docker run -p 5432:5432 -e POSTGRES_PASSWORD="=test==" -d postgres 		# this works
docker run -p 5432:5432 -e POSTGRES_PASSWORD="=d+\{&" -d postgres 		# this fails

**Comment by nakashimanh** [comment]
Thanks!
The password including slash is now available again ! 
-- Version 2019.06.11 (Build 110497.1)

**Comment by hankinsoft** [comment]
@martijnt ugh, still not able to reproduce using a password of '=d+{&'. What version of Postgres server are you running? (Sorry for so many questions, but without reproducing this its very hard to diagnose - especially when as far as I can tell I follow the proper connection string escaping listed on the Postgres docs).

<img width="1162" alt="Successful login after cresting user with password =d+{&" src="https://user-images.githubusercontent.com/3160528/59349067-2063e200-8cef-11e9-9426-4d722f493d14.png">

**Comment by martijnt** [comment]
Ouch. Found the problem. The command lines I provided above ended up wrong on Github; the last one contained a backslash, which got escaped. It turns out the problem is not with any of the above characters (they all work), but with the way SQL Pro handles backslashes. To reproduce:
- Start postgres: docker run -p 5432:5432 -e POSTGRES_PASSWORD="test" -d postgres 
- Confirm connecting with SQLPro still works
- Change password: ALTER ROLE postgres WITH PASSWORD 'test\\';
- At this stage it's not possible to login anymore using SQLPro using 'test\\' as pasword (it still works in Tableplus)

**Comment by hankinsoft** [comment]
Thanks, I was able to find an issue with the password 'test\'. I've got a fixed build available here: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.06.13.app.zip. If you get the chance, please give it a try and let me know.

**Comment by martijnt** [comment]
Can confirm it's working now. Thanks!
