### ISSUE TITLE
Feature Request: Autocomplete recognition of temp tables and transient tables

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#454]
If I have:
```
CREATE TEMP TABLE some_data_tmp AS

	SELECT query

;

SELECT
	*

FROM
	some_
```

I do not get any suggestions in the latter FROM for "some_", even though that's the name of my table. Same goes for columns of that table (even if qualified with the table).

I'd love to see autocomplete support for temp tables!

SQLPro Studio 2020.59 (Build 110683.5)
macOS 10.15.5 (19F101)

Present with at least Postgres 10.1 and Snowflake 4.21.3

**Comment by hankinsoft** [comment]
I'll have to think about this as it would require two things that SQLPro currently does not have:

1. Detection that a new table has been added.
2. Autocomplete `per tab`.

I have had item one planned for awhile as it ties into a very old change request (#10). Item two is something I will need to put some through into.

**Comment by jim256** [comment]
@hankinsoft, great to hear. Given the performance, I've now switched almost entirely from CTEs to temp tables and 0 autocomplete there is killing my query-writing speed. Thank you!

**Comment by jim256** [comment]
While we're on this topic, I'll also add that it'd probably nice to have transient tables added as well for those that use them. Your comment in the other issue about them made me think of this.

**Comment by jim256** [comment]
Hey, @hankinsoft.

Just wanted to give this one a bump as, like I mentioned in my last comments, I (and those on my team) now use temp tables very extensively and not having autocomplete is slowing us down a bit.

It seems like I saw point 1 from your last comment being mentioned in the releases notes in the last couple builds (does that also mean #10 can be closed?).

**Comment by jim256** [comment]
Seems like this has been resolved for Postgres?

**Comment by jim256** [comment]
Been holding back but want to give this another bump. Definitely a productivity killer to not have autocomplete, but definitely a time/cost killer to use CTEs instead to get it.

**Comment by richardo2008** [comment]
This would definitely increase productivity for me. I too am only using temp tables over CTEs.

**Comment by hankinsoft** [comment]
Working on this for one of the next builds.

**Comment by hankinsoft** [comment]
<img width="1162" alt="Screen Shot 2021-02-04 at 8 43 11 AM" src="https://user-images.githubusercontent.com/3160528/106894255-16150980-66c5-11eb-8488-a36e76629e0c.png">

I have some of the basics done. Still have a few more items:

1. I have to detect when temp tables are created. Because they can be created a few ways (`CREATE TEMP TABLE`, `SELECT * INTO`, or even via special table names `CREATE TABLE #TableName`) this is taking a bit of work.
2. Still need to handle syntax highlighting.
3. Still need to handle detection dropped temp tables so they do not appear in autocomplete if you drop them.

UNLIKE CTE's and Aliases, temp tables need to be created (run against the server) before the autocomplete will be available.

This will hopefully be available early/mid next week.

**Comment by hankinsoft** [comment]
The last few items ended up being easier than I expected. 2021.10 has been approved by apple and is now available in the store. If you get the chance, please give it a try.

**Comment by jim256** [comment]
So excited about this moving forward!

I don't have a SQL Server connection.
Doesn't seem to work with Snowflake 5.3.1, MySQL 8, or MySQL 5.7. I'm still using the CTAS syntax.

Still works in Postgres 10.13 as mentioned in [this comment](https://github.com/hankinsoft/SQLPro/issues/454#issuecomment-713660999)

SQLPro Studio 2021.10 (Build 110772.5)
macOS 11.1 (20C69)

**Comment by hankinsoft** [comment]
Could you post an example of the syntax you are using in both snowflake and mysql?

**Comment by jim256** [comment]
FYI, I just added a little detail to my previous comment before seeing yours.

For Snowflake, I'm using the same syntax as in the original/opening comment of this issue. For MySQL, I'm just using the full word `TEMPORARY` instead of `TEMP`.

**Comment by jim256** [comment]
Snowflake:
<img width="816" alt="image" src="https://user-images.githubusercontent.com/15026225/107069798-b0498000-679f-11eb-9075-f0a30dac6bb0.png">

MySQL:
![Uploading image.png…]()

**Comment by hankinsoft** [comment]
If you get the chance, please give this a try in the latest build.

**Comment by jim256** [comment]
This is so awesome!!! :partying_face: :tada: Thank you so much for making this happen. This will speed things up so much.

Looks like it even properly recognizes when the same alias is used for different tables in different statements, which is also excellent.

Example:
```
SELECT
	*

FROM
	PRODUCTS prod
;


SELECT
	*

FROM
	_tmp_products prod
;
```

Using `prod.` brings up the correct columns within each statement. Absolutely bomb.

**Comment by hankinsoft** [comment]
Great! Thanks for letting me know all is good.

**Comment by jim256** [comment]
@hankinsoft, I just noticed that, in Snowflake, this is case sensitive.

Example:
```
CREATE OR REPLACE TEMP TABLE _this_table AS
	....
;

SELECT
	*
FROM
	_thi
```

Produces no results. If I change the FROM to be `_THI`, then it pops up. If I type the table name on my own in lowercase letters and then alias it, the alias also won't produce any suggestions until I change the table name to be all caps.

As a side note, the case I use in the CTAS statement doesn't change anything since Snowflake converts all non-quoted identifiers to all caps anyway.

SQLPro Studio 2021.13 (Build 110775.5)
macOS 11.2.1 (20D74)
Snowflake 5.5.0

**Comment by jim256** [comment]
Just giving a bump to this one since it's 99% of the way there but not in use due to this.

**Comment by hankinsoft** [comment]
<img width="1382" alt="Screen Shot 2021-03-17 at 11 33 05 AM" src="https://user-images.githubusercontent.com/3160528/111484509-97c07400-8714-11eb-91b3-0cb5083a30a4.png">

Submitted the next build with a fix for this. Should be available in ~24 hours.

**Comment by jim256** [comment]
@hankinsoft 
Thanks a lot!

One more thing is that it still seems to be somewhat case sensitive. For example, I can type a table name in any case in the FROM, alias it, and autocomplete will recognize it. But for a temp table, I'm required to use all caps in the FROM, or autocomplete doesn't recognize it.

Example of lower case, not working:
<img width="402" alt="image" src="https://user-images.githubusercontent.com/15026225/111539462-86d32b00-8733-11eb-9407-c83e12fc6c34.png">


Example of all caps, working:
<img width="411" alt="image" src="https://user-images.githubusercontent.com/15026225/111539530-9a7e9180-8733-11eb-9606-0b1afac55485.png">



Also, FWIW, it seems that some UI changes maybe made it into this release. The app icon and server icons are different (matching your screenshot above). Just as one user's feedback, I think I personally preferred the prior versions.

**Comment by hankinsoft** [comment]
> One thing still seems case sensitive. For example, I can type a table name in any case in the FROM, alias it, and autocomplete will recognize it. But for a temp table, I'm required to use all caps in the FROM, or autocomplete doesn't recognize it.

Got it. Should have it fixed up for the next build.

> Also, FWIW, it seems that some UI changes maybe made it into this release. The app icon and server icons are different (matching your screenshot above). Just as one user's feedback, I think I personally preferred the prior versions.

As I've been getting a majoring of users switching to Big Sur, I've been switching to the big sir style guidelines which is very iOS like (rounded icons, etc).
