### ISSUE TITLE
Oracle cannot connect as sysdba

### ISSUE THREAD

**Issue by tkwintera** [hankinsoft/SQLPro#528]
When I attempt to login to Oracle with the role 'sysdba', the connection fails. After the attempt fails, the role in the connection setup reverts to 'default' instead of 'sysdba.'
<img width="532" alt="Screen Shot 2020-11-06 at 2 41 36 PM" src="https://user-images.githubusercontent.com/74075105/98412915-60dba280-203e-11eb-974f-519d06366d8f.png">

**Comment by hankinsoft** [comment]
I'm getting a fix for this submitted today. It should be available in the store in ~24 hours or so.

**Comment by hankinsoft** [comment]
This should be fixed in the latest build.

**Comment by hankinsoft** [comment]
Sorry it looks like only SQLPro for Oracle has been approved so far - if you are using SQLPro Studio it may still be a few hours.

**Comment by hankinsoft** [comment]
This should now be available in the latest version of the app. Please update and let me know if that helps out.

**Comment by tkwintera** [comment]
Hi, thanks for following-up. Unfortunately, I still receive the following error:


I am definitely selecting ’SYSDBA’ as the role. After it fails to login, the ‘role’ reverts back to ‘default.’ I’m using build 2020.85.

-Tony K.

**Comment by hankinsoft** [comment]
Hi - are you using the app store, or website version of SQLPro?

**Comment by tkwintera** [comment]
It must be the website version. I have to manually download and replace each time an update is available.

**Comment by hankinsoft** [comment]
Can you grab https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.100.app.zip?

**Comment by tkwintera** [comment]
That did it! I’m in. Thanks!

**Comment by hankinsoft** [comment]
No problem, thanks for letting me know.
